"""The ingestion contract: a normalised CI/CD failure."""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import ConfigDict, Field, StringConstraints, field_validator, model_validator

from autoheal_contracts.base import (
    CONTRACT_SCHEMA_VERSION,
    MAX_LOG_CHARS,
    ContractModel,
    ShortText,
    UTCDateTime,
    assert_not_in_future,
)
from autoheal_contracts.enums import FailureType

__all__ = ["FailureEvent"]

#: Incident ids are generated by the ingestion module and are the stable key
#: used by every other module, the API and the incident store.
INCIDENT_ID_PATTERN = r"^inc-[0-9]{8}-[0-9a-z]{6,12}$"

#: ``owner/repository`` -- deliberately not a full URL, because the remote host
#: is out of scope for this contract.
REPOSITORY_PATTERN = r"^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$"

#: A full git object name (SHA-1 40 hex chars, or a 7+ hex short form).
#: Upper-case input is accepted and normalised to lower-case, because build
#: systems do not agree on SHA rendering.
COMMIT_SHA_PATTERN = r"^[0-9a-fA-F]{7,64}$"

#: A normalised commit SHA: lowercase hexadecimal, 7 to 64 characters.
CommitSha = Annotated[
    str,
    StringConstraints(pattern=COMMIT_SHA_PATTERN, max_length=64),
]

#: A run URL is any absolute https URL. Stored verbatim for operator reference.
RunUrl = Annotated[
    str,
    StringConstraints(pattern=r"^https://", max_length=500),
]


class FailureEvent(ContractModel):
    """A CI/CD failure, normalised away from any specific provider.

    Produced by the ingestion module (Member 1) and consumed by the diagnosis
    module (Member 2) and by the API's ``POST /api/v1/incidents``.

    Field notes
    -----------
    ``schema_version``
        Always ``"1.0"``. Anything else is rejected, so a payload from a future
        contract revision fails loudly instead of being misread.
    ``incident_id``
        Client-supplied, stable, unique. Format ``inc-YYYYMMDD-<random6-12>``.
        Re-posting the same id returns ``409 Conflict`` from the API.
    ``commit_sha``
        Lower-cased; 7 to 64 hexadecimal characters.
    ``run_id``
        Numeric run identifier reported by the CI platform. Platforms with
        non-numeric run identifiers must map them to a numeric pipeline id.
    ``logs``
        Raw, unmodified log text. Only leading/trailing whitespace of the whole
        blob is stripped; internal formatting is preserved **exactly** so that
        :class:`~autoheal_contracts.diagnosis.EvidenceItem` quotes remain
        verifiable against it.
    ``timestamp``
        When the CI platform recorded the failure. Timezone aware, normalised
        to UTC; a timestamp more than 5 minutes in the future is rejected.
    """

    model_config = ConfigDict(extra="forbid", validate_assignment=True)

    schema_version: Literal[CONTRACT_SCHEMA_VERSION] = CONTRACT_SCHEMA_VERSION
    incident_id: Annotated[str, StringConstraints(pattern=INCIDENT_ID_PATTERN)]
    repository: Annotated[
        str,
        StringConstraints(pattern=REPOSITORY_PATTERN, min_length=3, max_length=200),
    ]
    commit_sha: CommitSha
    workflow_name: ShortText
    run_id: Annotated[int, Field(ge=0, le=2**63 - 1)]
    failed_step: ShortText
    failure_type: FailureType
    logs: Annotated[str, StringConstraints(min_length=1, max_length=MAX_LOG_CHARS)]
    timestamp: UTCDateTime

    # -- optional provider context ---------------------------------------
    branch: ShortText | None = None
    job_name: ShortText | None = None
    run_url: RunUrl | None = None
    pull_request_number: Annotated[int | None, Field(ge=1)] = None

    @model_validator(mode="after")
    def _reject_future_timestamps(self) -> FailureEvent:
        """Reject timestamps that sit beyond a small clock-skew tolerance."""
        assert_not_in_future(self.timestamp, "timestamp")
        return self

    @field_validator("commit_sha", mode="after")
    @classmethod
    def _normalise_sha(cls, value: str) -> str:
        """Normalise the SHA to lower-case, the canonical git rendering."""
        return value.lower()

    @model_validator(mode="after")
    def _reject_placeholder_logs(self) -> FailureEvent:
        """Reject log bodies that carry no information.

        ``logs`` is the only evidence source the diagnosis module can quote
        from, so accepting "n/a" here would let an empty diagnosis look
        evidence-backed.
        """
        if not self.logs.strip():
            raise ValueError("logs must contain at least one non-whitespace character")
        if len(self.logs.strip()) < 10:
            raise ValueError(
                "logs are too short to be evidence (minimum 10 significant characters)"
            )
        return self
